# Synthetic data generator for EDL banking schema (Postgres, multi-table, PK/FK)

This notebook generates synthetic data for the following EDL entities:

- Customer
- Branch
- Account
- Card
- Merchant
- Transaction
- Loan
- LoanPayment

It respects all primary/foreign key relationships, starting from small seed samples (e.g., 10 rows per table),
and writes the synthetic data into a Postgres database.

In [5]:
# Install dependencies (run once per environment)
#!pip install pandas sqlalchemy psycopg2-binary faker python-dateutil

In [6]:
import random
from datetime import datetime, timedelta

import pandas as pd
from faker import Faker
from sqlalchemy import create_engine, text
from dateutil.parser import parse as parse_date
import time

fake = Faker()
Faker.seed(42)
random.seed(42)

print("Imports, random seeds, and timing initialized.")

Imports, random seeds, and timing initialized.

In [7]:
# Demo: Generate American, Indian, and Spanish names with locale-specific Faker instances

fake_us = Faker("en_US")      # American English
fake_india = Faker("en_IN")   # Indian English
fake_spanish = Faker("es_ES") # Spanish (Spain)

print("US Name:      ", fake_us.name())
print("Indian Name:  ", fake_india.name())
print("Spanish Name: ", fake_spanish.name())

US Name:       Allison Hill
Indian Name:   Liam Chaudry
Spanish Name:  Antonia del Antón

## 1. Configure Postgres connection

Update the connection string with your actual Postgres credentials.

Example:
- `postgresql+psycopg2://postgres:password@localhost:5432/synthetic_db`

In [8]:
# TODO: Update this with your actual Postgres connection string
POSTGRES_CONN_STR = "postgresql+psycopg2://postgres:postgres@localhost:5432/finance_synth"

engine = create_engine(POSTGRES_CONN_STR)

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print("Postgres connection OK, test result:", list(result))

Postgres connection OK, test result: [(1,)]

## 2. Define schema metadata from EDL

The structure below mirrors the EDL entities and relationships:

- Customer (PK: customer_id)
- Branch (PK: branch_id)
- Account (PK: account_id, FK: customer_id → Customer, branch_id → Branch)
- Card (PK: card_id, FK: account_id → Account)
- Merchant (PK: merchant_id)
- Transaction (PK: txn_id, FK: account_id → Account, card_id → Card, merchant_id → Merchant)
- Loan (PK: loan_id, FK: customer_id → Customer, account_id → Account)
- LoanPayment (PK: payment_id, FK: loan_id → Loan)

Generation order respects dependencies so that FKs always reference existing rows.

In [9]:
SCHEMA_METADATA = {
    "tables": {
        "Customer": {
            "columns": {
                "customer_id": {"dtype": "string", "role": "pk"},
                "first_name": {"dtype": "string"},
                "last_name": {"dtype": "string"},
                "date_of_birth": {"dtype": "date"},
                "email": {"dtype": "email"},
                "ssn": {"dtype": "ssn"},
                "marketing_opt_in": {"dtype": "int"},
                "loyalty_points": {"dtype": "int"},
                "created_at": {"dtype": "timestamp"},
                "kyc_status": {"dtype": "string", "allowed_values": ["PENDING", "VERIFIED", "REJECTED"]}
            },
            "primary_key": ["customer_id"],
            "foreign_keys": []
        },
        "Branch": {
            "columns": {
                "branch_id": {"dtype": "string", "role": "pk"},
                "branch_name": {"dtype": "string"},
                "city": {"dtype": "string"},
                "country": {"dtype": "string"},
                "employee_count": {"dtype": "int"}
            },
            "primary_key": ["branch_id"],
            "foreign_keys": []
        },
        "Account": {
            "columns": {
                "account_id": {"dtype": "string", "role": "pk"},
                "customer_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Customer", "column": "customer_id"}
                },
                "branch_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Branch", "column": "branch_id"}
                },
                "account_type": {"dtype": "string", "allowed_values": ["SAVINGS", "CHECKING", "CREDIT", "LOAN"]},
                "currency": {"dtype": "string"},
                "opened_date": {"dtype": "date"},
                "status": {"dtype": "string", "allowed_values": ["ACTIVE", "BLOCKED", "CLOSED"]},
                "current_balance": {"dtype": "decimal"}
            },
            "primary_key": ["account_id"],
            "foreign_keys": [
                {"column": "customer_id", "ref_table": "Customer", "ref_column": "customer_id"},
                {"column": "branch_id", "ref_table": "Branch", "ref_column": "branch_id"}
            ]
        },
        "Card": {
            "columns": {
                "card_id": {"dtype": "string", "role": "pk"},
                "account_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Account", "column": "account_id"}
                },
                "card_number": {"dtype": "string"},
                "card_type": {"dtype": "string", "allowed_values": ["DEBIT", "CREDIT"]},
                "issued_date": {"dtype": "date"},
                "expiry_date": {"dtype": "date"},
                "status": {"dtype": "string", "allowed_values": ["ACTIVE", "BLOCKED", "EXPIRED"]}
            },
            "primary_key": ["card_id"],
            "foreign_keys": [
                {"column": "account_id", "ref_table": "Account", "ref_column": "account_id"}
            ]
        },
        "Merchant": {
            "columns": {
                "merchant_id": {"dtype": "string", "role": "pk"},
                "merchant_name": {"dtype": "string"},
                "category": {"dtype": "string"},
                "country": {"dtype": "string"}
            },
            "primary_key": ["merchant_id"],
            "foreign_keys": []
        },
        "Transaction": {
            "columns": {
                "txn_id": {"dtype": "string", "role": "pk"},
                "account_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Account", "column": "account_id"}
                },
                "card_id": {
                    "dtype": "string",
                    "role": "fk_optional",
                    "references": {"table": "Card", "column": "card_id"}
                },
                "merchant_id": {
                    "dtype": "string",
                    "role": "fk_optional",
                    "references": {"table": "Merchant", "column": "merchant_id"}
                },
                "txn_timestamp": {"dtype": "timestamp"},
                "amount": {"dtype": "decimal"},
                "currency": {"dtype": "string"},
                "exchange_rate": {"dtype": "double"},
                "txn_type": {"dtype": "string", "allowed_values": ["DEBIT", "CREDIT", "REFUND", "FEE"]},
                "status": {"dtype": "string", "allowed_values": ["PENDING", "POSTED", "REVERSED", "DECLINED"]}
            },
            "primary_key": ["txn_id"],
            "foreign_keys": [
                {"column": "account_id", "ref_table": "Account", "ref_column": "account_id", "nullable": False},
                {"column": "card_id", "ref_table": "Card", "ref_column": "card_id", "nullable": True},
                {"column": "merchant_id", "ref_table": "Merchant", "ref_column": "merchant_id", "nullable": True}
            ]
        },
        "Loan": {
            "columns": {
                "loan_id": {"dtype": "string", "role": "pk"},
                "customer_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Customer", "column": "customer_id"}
                },
                "account_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Account", "column": "account_id"}
                },
                "principal_amount": {"dtype": "decimal"},
                "interest_rate": {"dtype": "decimal"},
                "start_date": {"dtype": "date"},
                "end_date": {"dtype": "date"},
                "status": {"dtype": "string", "allowed_values": ["ACTIVE", "CLOSED", "DEFAULTED"]}
            },
            "primary_key": ["loan_id"],
            "foreign_keys": [
                {"column": "customer_id", "ref_table": "Customer", "ref_column": "customer_id"},
                {"column": "account_id", "ref_table": "Account", "ref_column": "account_id"}
            ]
        },
        "LoanPayment": {
            "columns": {
                "payment_id": {"dtype": "string", "role": "pk"},
                "loan_id": {
                    "dtype": "string",
                    "role": "fk",
                    "references": {"table": "Loan", "column": "loan_id"}
                },
                "payment_date": {"dtype": "date"},
                "amount": {"dtype": "decimal"},
                "method": {"dtype": "string", "allowed_values": ["TRANSFER", "CASH", "CARD"]}
            },
            "primary_key": ["payment_id"],
            "foreign_keys": [
                {"column": "loan_id", "ref_table": "Loan", "ref_column": "loan_id"}
            ]
        }
    },
    "generation_order": [
        "Customer",   
        "Branch",     
        "Account",    
        "Card",       
        "Merchant",   
        "Loan",       
        "LoanPayment",
        "Transaction" 
    ]
}

SCHEMA_METADATA

{'tables': {'Customer': {'columns': {'customer_id': {'dtype': 'string',
     'role': 'pk'},
    'first_name': {'dtype': 'string'},
    'last_name': {'dtype': 'string'},
    'date_of_birth': {'dtype': 'date'},
    'email': {'dtype': 'email'},
    'ssn': {'dtype': 'ssn'},
    'marketing_opt_in': {'dtype': 'int'},
    'loyalty_points': {'dtype': 'int'},
    'created_at': {'dtype': 'timestamp'},
    'kyc_status': {'dtype': 'string',
     'allowed_values': ['PENDING', 'VERIFIED', 'REJECTED']}},
   'primary_key': ['customer_id'],
   'foreign_keys': []},
  'Branch': {'columns': {'branch_id': {'dtype': 'string', 'role': 'pk'},
    'branch_name': {'dtype': 'string'},
    'city': {'dtype': 'string'},
    'country': {'dtype': 'string'},
    'employee_count': {'dtype': 'int'}},
   'primary_key': ['branch_id'],
   'foreign_keys': []},
  'Account': {'columns': {'account_id': {'dtype': 'string', 'role': 'pk'},
    'customer_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Customer', 'column': 'customer_id'}},
    'branch_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Branch', 'column': 'branch_id'}},
    'account_type': {'dtype': 'string',
     'allowed_values': ['SAVINGS', 'CHECKING', 'CREDIT', 'LOAN']},
    'currency': {'dtype': 'string'},
    'opened_date': {'dtype': 'date'},
    'status': {'dtype': 'string',
     'allowed_values': ['ACTIVE', 'BLOCKED', 'CLOSED']},
    'current_balance': {'dtype': 'decimal'}},
   'primary_key': ['account_id'],
   'foreign_keys': [{'column': 'customer_id',
     'ref_table': 'Customer',
     'ref_column': 'customer_id'},
    {'column': 'branch_id',
     'ref_table': 'Branch',
     'ref_column': 'branch_id'}]},
  'Card': {'columns': {'card_id': {'dtype': 'string', 'role': 'pk'},
    'account_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Account', 'column': 'account_id'}},
    'card_number': {'dtype': 'string'},
    'card_type': {'dtype': 'string', 'allowed_values': ['DEBIT', 'CREDIT']},
    'issued_date': {'dtype': 'date'},
    'expiry_date': {'dtype': 'date'},
    'status': {'dtype': 'string',
     'allowed_values': ['ACTIVE', 'BLOCKED', 'EXPIRED']}},
   'primary_key': ['card_id'],
   'foreign_keys': [{'column': 'account_id',
     'ref_table': 'Account',
     'ref_column': 'account_id'}]},
  'Merchant': {'columns': {'merchant_id': {'dtype': 'string', 'role': 'pk'},
    'merchant_name': {'dtype': 'string'},
    'category': {'dtype': 'string'},
    'country': {'dtype': 'string'}},
   'primary_key': ['merchant_id'],
   'foreign_keys': []},
  'Transaction': {'columns': {'txn_id': {'dtype': 'string', 'role': 'pk'},
    'account_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Account', 'column': 'account_id'}},
    'card_id': {'dtype': 'string',
     'role': 'fk_optional',
     'references': {'table': 'Card', 'column': 'card_id'}},
    'merchant_id': {'dtype': 'string',
     'role': 'fk_optional',
     'references': {'table': 'Merchant', 'column': 'merchant_id'}},
    'txn_timestamp': {'dtype': 'timestamp'},
    'amount': {'dtype': 'decimal'},
    'currency': {'dtype': 'string'},
    'exchange_rate': {'dtype': 'double'},
    'txn_type': {'dtype': 'string',
     'allowed_values': ['DEBIT', 'CREDIT', 'REFUND', 'FEE']},
    'status': {'dtype': 'string',
     'allowed_values': ['PENDING', 'POSTED', 'REVERSED', 'DECLINED']}},
   'primary_key': ['txn_id'],
   'foreign_keys': [{'column': 'account_id',
     'ref_table': 'Account',
     'ref_column': 'account_id',
     'nullable': False},
    {'column': 'card_id',
     'ref_table': 'Card',
     'ref_column': 'card_id',
     'nullable': True},
    {'column': 'merchant_id',
     'ref_table': 'Merchant',
     'ref_column': 'merchant_id',
     'nullable': True}]},
  'Loan': {'columns': {'loan_id': {'dtype': 'string', 'role': 'pk'},
    'customer_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Customer', 'column': 'customer_id'}},
    'account_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Account', 'column': 'account_id'}},
    'principal_amount': {'dtype': 'decimal'},
    'interest_rate': {'dtype': 'decimal'},
    'start_date': {'dtype': 'date'},
    'end_date': {'dtype': 'date'},
    'status': {'dtype': 'string',
     'allowed_values': ['ACTIVE', 'CLOSED', 'DEFAULTED']}},
   'primary_key': ['loan_id'],
   'foreign_keys': [{'column': 'customer_id',
     'ref_table': 'Customer',
     'ref_column': 'customer_id'},
    {'column': 'account_id',
     'ref_table': 'Account',
     'ref_column': 'account_id'}]},
  'LoanPayment': {'columns': {'payment_id': {'dtype': 'string', 'role': 'pk'},
    'loan_id': {'dtype': 'string',
     'role': 'fk',
     'references': {'table': 'Loan', 'column': 'loan_id'}},
    'payment_date': {'dtype': 'date'},
    'amount': {'dtype': 'decimal'},
    'method': {'dtype': 'string',
     'allowed_values': ['TRANSFER', 'CASH', 'CARD']}},
   'primary_key': ['payment_id'],
   'foreign_keys': [{'column': 'loan_id',
     'ref_table': 'Loan',
     'ref_column': 'loan_id'}]}},
 'generation_order': ['Customer',
  'Branch',
  'Account',
  'Card',
  'Merchant',
  'Loan',
  'LoanPayment',
  'Transaction']}

## 3. Load seed data (10 rows per table)

Assume you have one CSV file per entity with ~10 rows. Example filenames:

- `seed_Customer.csv`
- `seed_Branch.csv`
- `seed_Account.csv`
- `seed_Card.csv`
- `seed_Merchant.csv`
- `seed_Transaction.csv`
- `seed_Loan.csv`
- `seed_LoanPayment.csv`

Adjust paths or replace CSV loading with DB queries as needed.

In [10]:
SEED_DATA_PATHS = {
    "Customer": "./seed_Customer.csv",
    "Branch": "./seed_Branch.csv",
    "Account": "./seed_Account.csv",
    "Card": "./seed_Card.csv",
    "Merchant": "./seed_Merchant.csv",
    "Transaction": "./seed_Transaction.csv",
    "Loan": "./seed_Loan.csv",
    "LoanPayment": "./seed_LoanPayment.csv"
}

def load_seed_data(table_name: str) -> pd.DataFrame:
    path = SEED_DATA_PATHS.get(table_name)
    if path is None:
        raise ValueError(f"No seed data path configured for table: {table_name}")
    df = pd.read_csv(path)
    print(f"Loaded seed data for {table_name}: {df.shape[0]} rows, {df.shape[1]} columns")
    return df

# Quick smoke test for one table (comment out if files not yet ready)
try:
    seed_customer = load_seed_data("Customer")
    display(seed_customer.head())
except Exception as e:
    print("Seed Customer load skipped or failed:", e)

Loaded seed data for Customer: 10 rows, 10 columns

,customer_id,first_name,last_name,date_of_birth,email,ssn,marketing_opt_in,loyalty_points,created_at,kyc_status
0,CUST001,Alice,Smith,1985-01-15,alice.smith@example.com,123-45-6789,1,1200,2023-01-01 09:00:00,VERIFIED
1,CUST002,Bob,Johnson,1978-03-22,bob.johnson@example.com,234-56-7890,0,800,2023-01-02 10:15:00,PENDING
2,CUST003,Carol,Williams,1990-07-05,carol.williams@example.com,345-67-8901,1,500,2023-01-03 11:30:00,VERIFIED
3,CUST004,David,Brown,1982-11-09,david.brown@example.com,456-78-9012,1,1500,2023-01-04 14:45:00,VERIFIED
4,CUST005,Eva,Jones,1995-02-18,eva.jones@example.com,567-89-0123,0,300,2023-01-05 16:00:00,REJECTED

## 4. Helper functions: basic distribution inference and generators

We map EDL types to simple synthetic generators:

- `string` → Faker (names, country, generic word) or sampled from seed values
- `email` → Faker email
- `ssn` → Faker SSN-like value
- `int` → uniform or categorical
- `decimal`/`double` → numeric range
- `date` → random between min/max
- `timestamp` → random between min/max seed timestamps

This is intentionally simple and deterministic – you can refine per column later.

In [11]:
def infer_categorical_distribution(series: pd.Series):
    s = series.dropna()
    if s.empty:
        return lambda: None
    value_counts = s.value_counts(normalize=True)
    categories = value_counts.index.tolist()
    probabilities = value_counts.values.tolist()
    
    def sampler():
        return random.choices(categories, probabilities, k=1)[0]
    
    return sampler


def infer_numeric_range(series: pd.Series):
    s = series.dropna()
    if s.empty:
        return lambda: None
    min_val = float(s.min())
    max_val = float(s.max())
    
    def sampler():
        return random.uniform(min_val, max_val)
    
    return sampler


def infer_int_range(series: pd.Series):
    s = series.dropna()
    if s.empty:
        return lambda: None
    min_val = int(s.min())
    max_val = int(s.max())
    
    def sampler():
        return random.randint(min_val, max_val)
    
    return sampler


def infer_date_range(series: pd.Series):
    s = series.dropna()
    if s.empty:
        return lambda: None
    dates = s.apply(lambda x: parse_date(str(x))).sort_values()
    min_date = dates.min()
    max_date = dates.max()
    delta_days = (max_date - min_date).days or 1
    
    def sampler():
        offset = random.randint(0, delta_days)
        return (min_date + timedelta(days=offset)).date()
    
    return sampler


def infer_timestamp_range(series: pd.Series):
    s = series.dropna()
    if s.empty:
        return lambda: None
    ts = s.apply(lambda x: parse_date(str(x))).sort_values()
    min_ts = ts.min()
    max_ts = ts.max()
    delta_seconds = int((max_ts - min_ts).total_seconds()) or 1
    
    def sampler():
        offset = random.randint(0, delta_seconds)
        return min_ts + timedelta(seconds=offset)
    
    return sampler


def build_column_generators(table_name: str, seed_df: pd.DataFrame, schema: dict):
    table_meta = schema["tables"][table_name]
    col_generators = {}
    
    for col_name, col_info in table_meta["columns"].items():
        role = col_info.get("role")
        if role in ("pk", "fk", "fk_optional"):
            continue
        
        dtype = col_info.get("dtype")
        allowed_values = col_info.get("allowed_values")
        series = seed_df[col_name] if col_name in seed_df.columns else pd.Series([], dtype="object")
        unique_count = series.nunique(dropna=True)
        
        # If ALLOWED_VALUES defined, always sample from them
        if allowed_values:
            def make_sampler(values):
                def sampler():
                    return random.choice(values)
                return sampler
            col_generators[col_name] = make_sampler(allowed_values)
            continue
        
        if dtype == "string":
            if unique_count > 0 and unique_count <= 10:
                col_generators[col_name] = infer_categorical_distribution(series)
            else:
                if "country" in col_name.lower():
                    col_generators[col_name] = lambda: fake.country()
                elif "city" in col_name.lower():
                    col_generators[col_name] = lambda: fake.city()
                elif "name" in col_name.lower():
                    col_generators[col_name] = lambda: fake.word().title()
                else:
                    col_generators[col_name] = lambda: fake.word()
        elif dtype == "email":
            col_generators[col_name] = lambda: fake.email()
        elif dtype == "ssn":
            col_generators[col_name] = lambda: fake.ssn()
        elif dtype == "int":
            if unique_count > 0 and unique_count <= 10:
                col_generators[col_name] = infer_categorical_distribution(series)
            else:
                col_generators[col_name] = infer_int_range(series)
        elif dtype in ("decimal", "double"):
            col_generators[col_name] = infer_numeric_range(series)
        elif dtype == "date":
            col_generators[col_name] = infer_date_range(series)
        elif dtype == "timestamp":
            col_generators[col_name] = infer_timestamp_range(series)
        else:
            if unique_count > 0:
                col_generators[col_name] = infer_categorical_distribution(series)
            else:
                col_generators[col_name] = lambda: None
    
    return col_generators

print("Helper functions defined.")

Helper functions defined.

## 5. Synthetic generation for a single table (PK/FK aware)

Rules:

- PKs: generated as UUID-like or sequence for string IDs
- FKs: sampled from parent synthetic PK values
- Optional FKs (e.g., `Transaction.card_id`, `Transaction.merchant_id`): sometimes NULL
- Non-key columns: generated via the column generators built above.

In [12]:
import uuid

def generate_string_id(prefix: str = "ID", max_length: int = 16):
    """Generate a short string ID that fits into varchar(max_length).
    Currently unused for PKs but kept for flexibility.
    """
    base = prefix.upper()
    suffix = uuid.uuid4().hex
    if len(base) >= max_length:
        return base[:max_length]
    remaining = max_length - len(base) - 1  # for '_'
    if remaining <= 0:
        return base[:max_length]
    return f"{base}_" + suffix[:remaining]


def generate_synthetic_table(
    table_name: str,
    n_rows: int,
    schema_meta: dict,
    seed_df: pd.DataFrame,
    parent_data: dict
) -> pd.DataFrame:
    table_def = schema_meta["tables"][table_name]
    cols_def = table_def["columns"]
    pk_cols = table_def.get("primary_key", [])
    fk_defs = table_def.get("foreign_keys", [])
    
    col_generators = build_column_generators(table_name, seed_df, schema_meta)
    data = {col: [] for col in cols_def.keys()}
    
    # Prepare FK parent pools
    fk_value_pools = {}
    fk_nullable_flags = {}
    for fk in fk_defs:
        fk_col = fk["column"]
        ref_table = fk["ref_table"]
        ref_col = fk["ref_column"]
        nullable = fk.get("nullable", False)
        parent_df = parent_data.get(ref_table)
        if parent_df is None or parent_df.empty:
            # For safety; in practice you should always generate parents first
            raise ValueError(f"Parent table {ref_table} has not been generated or is empty (for FK {fk_col} in {table_name}).")
        fk_value_pools[fk_col] = parent_df[ref_col].tolist()
        fk_nullable_flags[fk_col] = nullable
    
    for i in range(n_rows):
        # PK generation (single-column string PKs, deterministic, max 16 chars)
        if pk_cols:
            pk_col = pk_cols[0]
            prefix = pk_col.upper()[:8]
            pk_val = f"{prefix}_{i+1:07d}"  # 8 + 1 + 7 = 16 chars
            data[pk_col].append(pk_val)
        
        # FK columns
        for fk in fk_defs:
            fk_col = fk["column"]
            pool = fk_value_pools[fk_col]
            nullable = fk_nullable_flags.get(fk_col, False)
            if nullable and random.random() < 0.2:
                # 20% NULLs for optional FKs
                data[fk_col].append(None)
            else:
                data[fk_col].append(random.choice(pool))
        
        # Non-PK/FK columns
        for col_name, col_info in cols_def.items():
            if col_name in pk_cols:
                continue
            if any(fk_col == col_name for fk_col in fk_value_pools.keys()):
                continue
            gen = col_generators.get(col_name)
            value = gen() if gen is not None else None
            data[col_name].append(value)
    
    df = pd.DataFrame(data)
    return df

print("Synthetic table generator defined.")

Synthetic table generator defined.

## 6. Orchestrate multi-table generation (respecting EDL relationships)

Configure how many synthetic rows you want per table. Start small for testing, then scale up.

You can absolutely go from 10 → 1000 rows here (and later to 1M) – the logic doesn’t change.

In [13]:
# Configure synthetic row targets per table
TARGET_ROWS = {
    "Customer": 100,
    "Branch": 20,
    "Account": 300,
    "Card": 400,
    "Merchant": 100,
    "Loan": 80,
    "LoanPayment": 300,
    "Transaction": 500
}

synthetic_data = {}

print("Starting synthetic data generation at", datetime.now())
gen_start = time.perf_counter()

for table_name in SCHEMA_METADATA["generation_order"]:
    n_rows = TARGET_ROWS.get(table_name, 1000)
    print(f"\n=== Generating table: {table_name} ({n_rows} rows) ===")
    seed_df = load_seed_data(table_name)
    df_syn = generate_synthetic_table(
        table_name=table_name,
        n_rows=n_rows,
        schema_meta=SCHEMA_METADATA,
        seed_df=seed_df,
        parent_data=synthetic_data
)
    synthetic_data[table_name] = df_syn
    display(df_syn.head())
    print("Generated shape:", df_syn.shape)

print("\nAll tables generated.")
gen_end = time.perf_counter()
print("Finished synthetic data generation at", datetime.now())
print(f"Total generation time: {gen_end - gen_start:.2f} seconds")

Starting synthetic data generation at 2026-01-15 14:23:38.815509

=== Generating table: Customer (100 rows) ===
Loaded seed data for Customer: 10 rows, 10 columns

,customer_id,first_name,last_name,date_of_birth,email,ssn,marketing_opt_in,loyalty_points,created_at,kyc_status
0,CUSTOMER_0000001,Grace,Smith,1981-11-30,davisjesse@example.net,028-72-3258,1,800,2023-01-02 14:51:13,REJECTED
1,CUSTOMER_0000002,Henry,Miller,1988-12-27,lrobinson@example.com,829-01-2616,1,1200,2023-01-04 00:40:58,PENDING
2,CUSTOMER_0000003,Frank,Smith,1980-03-15,jpeterson@example.org,782-44-1675,0,1100,2023-01-06 11:11:38,PENDING
3,CUSTOMER_0000004,Eva,Williams,1975-11-22,jamesmichael@example.com,619-34-0712,0,800,2023-01-06 12:05:43,VERIFIED
4,CUSTOMER_0000005,Carol,Williams,1992-11-13,yherrera@example.org,566-38-5926,1,1200,2023-01-02 13:10:14,VERIFIED

Generated shape: (100, 10)

=== Generating table: Branch (20 rows) ===
Loaded seed data for Branch: 10 rows, 5 columns

          branch_id         branch_name     city country  employee_count
0  BRANCH_I_0000001      Central Branch  Chicago      UK              45
1  BRANCH_I_0000002     Lakeside Branch  Chicago      UK              40
2  BRANCH_I_0000003     West End Branch   London     USA              60
3  BRANCH_I_0000004      Central Branch   London     USA             150
4  BRANCH_I_0000005  City Center Branch   London     USA              60

Generated shape: (20, 5)

=== Generating table: Account (300 rows) ===
Loaded seed data for Account: 10 rows, 8 columns

,account_id,customer_id,branch_id,account_type,currency,opened_date,status,current_balance
0,ACCOUNT__0000001,CUSTOMER_0000057,BRANCH_I_0000010,LOAN,USD,2021-02-10,ACTIVE,5668.540964
1,ACCOUNT__0000002,CUSTOMER_0000095,BRANCH_I_0000004,CHECKING,AUD,2019-02-11,CLOSED,-3579.219354
2,ACCOUNT__0000003,CUSTOMER_0000031,BRANCH_I_0000006,SAVINGS,USD,2019-12-03,BLOCKED,7063.994876
3,ACCOUNT__0000004,CUSTOMER_0000061,BRANCH_I_0000010,SAVINGS,USD,2021-08-05,BLOCKED,7302.282267
4,ACCOUNT__0000005,CUSTOMER_0000059,BRANCH_I_0000003,CHECKING,HKD,2021-02-19,CLOSED,6570.703250

Generated shape: (300, 8)

=== Generating table: Card (400 rows) ===
Loaded seed data for Card: 10 rows, 7 columns

,card_id,account_id,card_number,card_type,issued_date,expiry_date,status
0,CARD_ID_0000001,ACCOUNT__0000232,5500000000000004,CREDIT,2017-12-01,2025-08-26,ACTIVE
1,CARD_ID_0000002,ACCOUNT__0000012,4111111111111152,DEBIT,2021-06-18,2022-08-03,EXPIRED
2,CARD_ID_0000003,ACCOUNT__0000125,5500000000000020,DEBIT,2019-07-10,2024-10-21,BLOCKED
3,CARD_ID_0000004,ACCOUNT__0000237,4111111111111137,CREDIT,2021-03-13,2022-09-13,ACTIVE
4,CARD_ID_0000005,ACCOUNT__0000222,5500000000000004,DEBIT,2020-03-09,2024-12-26,BLOCKED

Generated shape: (400, 7)

=== Generating table: Merchant (100 rows) ===
Loaded seed data for Merchant: 10 rows, 4 columns

        merchant_id merchant_name     category    country
0  MERCHANT_0000001     TechWorld   RESTAURANT        USA
1  MERCHANT_0000002      FuelPlus  GAS_STATION        USA
2  MERCHANT_0000003     TravelNow      GROCERY      China
3  MERCHANT_0000004      StyleHub      GROCERY  Singapore
4  MERCHANT_0000005    BookCorner   HOME_GOODS        USA

Generated shape: (100, 4)

=== Generating table: Loan (80 rows) ===
Loaded seed data for Loan: 10 rows, 8 columns

,loan_id,customer_id,account_id,principal_amount,interest_rate,start_date,end_date,status
0,LOAN_ID_0000001,CUSTOMER_0000028,ACCOUNT__0000162,2923.176743,5.876790,2021-08-07,2026-07-16,CLOSED
1,LOAN_ID_0000002,CUSTOMER_0000071,ACCOUNT__0000262,13348.300167,6.240729,2018-08-07,2022-06-16,ACTIVE
2,LOAN_ID_0000003,CUSTOMER_0000059,ACCOUNT__0000183,5544.088574,3.927459,2020-12-30,2023-04-30,ACTIVE
3,LOAN_ID_0000004,CUSTOMER_0000033,ACCOUNT__0000154,4292.149865,4.399294,2018-12-14,2026-01-16,ACTIVE
4,LOAN_ID_0000005,CUSTOMER_0000093,ACCOUNT__0000167,17961.631789,3.605159,2021-08-07,2025-11-13,DEFAULTED

Generated shape: (80, 8)

=== Generating table: LoanPayment (300 rows) ===
Loaded seed data for LoanPayment: 10 rows, 5 columns

         payment_id          loan_id payment_date      amount    method
0  PAYMENT__0000001  LOAN_ID_0000037   2019-03-30  416.078201      CASH
1  PAYMENT__0000002  LOAN_ID_0000039   2020-08-27  319.997440  TRANSFER
2  PAYMENT__0000003  LOAN_ID_0000015   2021-08-29  233.313156      CASH
3  PAYMENT__0000004  LOAN_ID_0000073   2021-04-08  484.045130  TRANSFER
4  PAYMENT__0000005  LOAN_ID_0000025   2019-09-01  433.530120      CARD

Generated shape: (300, 5)

=== Generating table: Transaction (500 rows) ===
Loaded seed data for Transaction: 10 rows, 10 columns

,txn_id,account_id,card_id,merchant_id,txn_timestamp,amount,currency,exchange_rate,txn_type,status
0,TXN_ID_0000001,ACCOUNT__0000140,CARD_ID_0000285,MERCHANT_0000073,2023-01-03 01:57:58,118.390545,EUR,0.439726,FEE,PENDING
1,TXN_ID_0000002,ACCOUNT__0000155,CARD_ID_0000156,MERCHANT_0000095,2023-01-07 01:04:24,132.322902,SGD,0.294806,REFUND,DECLINED
2,TXN_ID_0000003,ACCOUNT__0000064,CARD_ID_0000148,MERCHANT_0000063,2023-01-09 18:25:55,364.099394,USD,0.948249,FEE,PENDING
3,TXN_ID_0000004,ACCOUNT__0000186,CARD_ID_0000290,MERCHANT_0000034,2023-01-09 01:00:01,386.780929,HKD,1.005560,REFUND,PENDING
4,TXN_ID_0000005,ACCOUNT__0000133,None,None,2023-01-05 07:11:49,262.765748,AUD,0.512402,DEBIT,REVERSED

Generated shape: (500, 10)

All tables generated.
Finished synthetic data generation at 2026-01-15 14:23:39.068644
Total generation time: 0.25 seconds

## 7. Write synthetic data into Postgres

Write in the same order, using `if_exists='replace'` for clean runs.

Table names in Postgres match the EDL entity names (case-sensitive behavior depends on your Postgres settings – you can lower-case if you prefer).

In [16]:
# Clear existing data while keeping schema & constraints
from sqlalchemy import text
from sqlalchemy.exc import ProgrammingError

print("Starting write to Postgres at", datetime.now())
write_start = time.perf_counter()

with engine.begin() as conn:
    try:
        conn.execute(text(
            'TRUNCATE TABLE "Transaction", "LoanPayment", "Loan", "Card", "Account", "Merchant", "Branch", "Customer" RESTART IDENTITY CASCADE'
        ))
    except ProgrammingError as e:
        print("Warning: TRUNCATE failed, skipping truncate step. Error:", e)

for table_name in SCHEMA_METADATA["generation_order"]:
    df = synthetic_data[table_name]
    print(f"Writing {table_name} to Postgres: {df.shape[0]} rows")
    df.to_sql(table_name, engine, if_exists="append", index=False)

print("All tables written to Postgres.")
write_end = time.perf_counter()
print("Finished write to Postgres at", datetime.now())
print(f"Total write time: {write_end - write_start:.2f} seconds")

Starting write to Postgres at 2026-01-15 14:28:36.994317
Warning: TRUNCATE failed, skipping truncate step. Error: (psycopg2.errors.UndefinedTable) relation "Transaction" does not exist

[SQL: TRUNCATE TABLE "Transaction", "LoanPayment", "Loan", "Card", "Account", "Merchant", "Branch", "Customer" RESTART IDENTITY CASCADE]
(Background on this error at: https://sqlalche.me/e/20/f405)
Writing Customer to Postgres: 100 rows
Writing Branch to Postgres: 20 rows
Writing Account to Postgres: 300 rows
Writing Card to Postgres: 400 rows
Writing Merchant to Postgres: 100 rows
Writing Loan to Postgres: 80 rows
Writing LoanPayment to Postgres: 300 rows
Writing Transaction to Postgres: 500 rows
All tables written to Postgres.
Finished write to Postgres at 2026-01-15 14:28:37.546247
Total write time: 0.55 seconds

## 8. Basic PK/FK validation in Postgres

Simple checks:

- Row counts per table
- FK integrity for the main relationships

You can add more checks (uniqueness, null constraints, ranges) as needed.

In [17]:
with engine.connect() as conn:
    print("Row counts in Postgres:")
    for table_name in SCHEMA_METADATA["generation_order"]:
        result = conn.execute(text(f"SELECT COUNT(*) FROM \"{table_name}\""))
        count = list(result)[0][0]
        print(f"- {table_name}: {count}")
    
    print("\nFK checks:")
    # Account.customer_id -> Customer.customer_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "Account" a
        LEFT JOIN "Customer" c ON a.customer_id = c.customer_id
        WHERE c.customer_id IS NULL
        """
    ))
    print("Account.customer_id missing Customer:", list(result)[0][0])
    
    # Account.branch_id -> Branch.branch_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "Account" a
        LEFT JOIN "Branch" b ON a.branch_id = b.branch_id
        WHERE b.branch_id IS NULL
        """
    ))
    print("Account.branch_id missing Branch:", list(result)[0][0])
    
    # Card.account_id -> Account.account_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "Card" c
        LEFT JOIN "Account" a ON c.account_id = a.account_id
        WHERE a.account_id IS NULL
        """
    ))
    print("Card.account_id missing Account:", list(result)[0][0])
    
    # Transaction.account_id -> Account.account_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "Transaction" t
        LEFT JOIN "Account" a ON t.account_id = a.account_id
        WHERE a.account_id IS NULL
        """
    ))
    print("Transaction.account_id missing Account:", list(result)[0][0])
    
    # Loan.customer_id -> Customer.customer_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "Loan" l
        LEFT JOIN "Customer" c ON l.customer_id = c.customer_id
        WHERE c.customer_id IS NULL
        """
    ))
    print("Loan.customer_id missing Customer:", list(result)[0][0])
    
    # Loan.account_id -> Account.account_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "Loan" l
        LEFT JOIN "Account" a ON l.account_id = a.account_id
        WHERE a.account_id IS NULL
        """
    ))
    print("Loan.account_id missing Account:", list(result)[0][0])
    
    # LoanPayment.loan_id -> Loan.loan_id
    result = conn.execute(text(
        """
        SELECT COUNT(*)
        FROM "LoanPayment" p
        LEFT JOIN "Loan" l ON p.loan_id = l.loan_id
        WHERE l.loan_id IS NULL
        """
    ))
    print("LoanPayment.loan_id missing Loan:", list(result)[0][0])

Row counts in Postgres:
- Customer: 100
- Branch: 20
- Account: 300
- Card: 400
- Merchant: 100
- Loan: 80
- LoanPayment: 300
- Transaction: 500

FK checks:
Account.customer_id missing Customer: 0
Account.branch_id missing Branch: 0
Card.account_id missing Account: 0
Transaction.account_id missing Account: 0
Loan.customer_id missing Customer: 0
Loan.account_id missing Account: 0
LoanPayment.loan_id missing Loan: 0

## 9. Next steps / customization

- Plug in your real 10-row samples into the seed CSVs
- Tune `TARGET_ROWS` to scale (1000, 10k, 100k, 1M)
- Refine column generators to be finance-specific (IBAN, BIN ranges, realistic balances)
- Externalize `SCHEMA_METADATA` to JSON/YAML and reuse across pipelines
- Add more validations: value ranges, null checks, uniqueness constraints